id: Endpoint Enrichment By EntityId - XM Cyber
version: 5
vcShouldKeepItemLegacyProdMachine: false
name: Endpoint Enrichment By EntityId - XM Cyber
description: Enrich an endpoint by entityId using XM Cyber integration. Outputs include
  affected assets, affected entities, complexity of compromise, and more
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 58b90b77-70fd-466c-8953-6e90da525300
    type: start
    task:
      id: 58b90b77-70fd-466c-8953-6e90da525300
      version: -1
      name: ""
      description: Start
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 1dd7be88-cb65-4f1e-8c37-9aad6fc1339b
    type: title
    task:
      id: 1dd7be88-cb65-4f1e-8c37-9aad6fc1339b
      version: -1
      name: XM Cyber Available
      description: XM Cyber Available
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 275,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 7d9ec595-73aa-4b56-8eb5-547d4d40f551
    type: condition
    task:
      id: 7d9ec595-73aa-4b56-8eb5-547d4d40f551
      version: -1
      name: Is there an endpoint to enrich?
      description: Checks whether there is at least one endpoint to enrich (by entityId).
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "5"
    scriptarguments:
      value:
        simple: ${incident.labels.entityId}
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: inputs.EntityId
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 7ae31b6f-572d-4545-8aba-258262284a21
    type: title
    task:
      id: 7ae31b6f-572d-4545-8aba-258262284a21
      version: -1
      name: Done
      description: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1390
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: c07df85d-fb6e-4b0a-81ac-e08eb600545e
    type: condition
    task:
      id: c07df85d-fb6e-4b0a-81ac-e08eb600545e
      version: -1
      name: Is XM Cyber Available
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'
      scriptName: IsIntegrationAvailable
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "1"
    scriptarguments:
      brandname:
        simple: XMCyber
    results:
    - brandInstances
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 5c10dbfc-ff19-4a2d-851e-88fc6750f59e
    type: regular
    task:
      id: 5c10dbfc-ff19-4a2d-851e-88fc6750f59e
      version: -1
      name: Enrich from entityId
      description: Return data on Entity by entityId from XM Cyber
      script: '|||xmcyber-enrich-from-entityId'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      entityId:
        simple: ${inputs.EntityId}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 275,
          "y": 690
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    fieldMapping:
    - incidentfield: Entity ID
      output:
        simple: ${XMCyber.Entity.id}
    - incidentfield: Entity name
      output:
        simple: ${XMCyber.Entity.name}
    - incidentfield: Entity is a critical asset
      output:
        simple: ${XMCyber.Entity.isAsset}
    - incidentfield: Affected Entities
      output:
        simple: ${XMCyber.Entity.affectedEntities}
    - incidentfield: Avg. complexity score
      output:
        simple: ${XMCyber.Entity.averageComplexity}
    - incidentfield: Critical Assets At Risk
      output:
        simple: ${XMCyber.Entity.criticalAssetsAtRisk}
    - incidentfield: Avg. complexity level
      output:
        simple: ${XMCyber.Entity.averageComplexityLevel}
    - incidentfield: Entity type
      output:
        simple: ${XMCyber.Entity.type}
    - incidentfield: Entity report
      output:
        simple: ${XMCyber.Entity.report}
    - incidentfield: Compromising Techniques
      output:
        simple: ${XMCyber.Entity.compromisingTechniques}
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: eaee32d9-0027-44e8-877a-47d7b0935378
    type: regular
    task:
      id: eaee32d9-0027-44e8-877a-47d7b0935378
      version: -1
      name: Get Critical Assets At Risk
      description: List critical assets at risk from an entity and the complexity
        of the attack
      script: '|||xmcyber-affected-critical-assets-list'
      type: regular
      iscommand: true
      brand: XMCyber
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      entityId:
        simple: ${XMCyber.Entity.id}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 510,
          "y": 1040
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    fieldMapping:
    - incidentfield: Critical Assets At Risk List
      output:
        simple: ${XMCyber.Entity.criticalAssetsAtRiskList}
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: aaff82a1-9a8e-4dda-88a3-4fac5979699b
    type: regular
    task:
      id: aaff82a1-9a8e-4dda-88a3-4fac5979699b
      version: -1
      name: Get Entities At Risk
      description: List all entities at risk from an entity and the complexity of
        the attack
      script: '|||xmcyber-affected-entities-list'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      entityId:
        simple: ${XMCyber.Entity.id}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 510,
          "y": 1190
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    fieldMapping:
    - incidentfield: Affected Entities List
      output:
        simple: ${XMCyber.Entity.entitiesAtRiskList}
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 4589b6d0-27ce-4208-87c9-351a628ef7f7
    type: condition
    task:
      id: 4589b6d0-27ce-4208-87c9-351a628ef7f7
      version: -1
      name: Found Entity?
      description: Does the endpoint match an XM Cyber entity?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "7"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: ${XMCyber.Entity.id}
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 275,
          "y": 865
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "3_4_#default#": 0.12
    },
    "paper": {
      "dimensions": {
        "height": 1405,
        "width": 840,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: EntityId
  value:
    complex:
      root: incident
      accessor: entityid
  required: false
  description: ""
  playbookInputQuery: null
outputs:
- contextPath: Endpoint
  description: The endpoint object of the endpoint that was enriched.
  type: unknown
- contextPath: Endpoint.Hostname
  description: The hostnames of the endpoints that were enriched.
  type: string
- contextPath: Endpoint.OS
  description: The operating systems running on the endpoints that were enriched.
  type: string
- contextPath: Endpoint.IP
  description: A list of the IP addresses of the endpoints.
  type: string
- contextPath: XMCyber.Entity.isAsset
  description: Entity is a critical asset
  type: boolean
- contextPath: XMCyber.Entity.affectedEntities
  description: Number of unique entities at risk from this entity
  type: number
- contextPath: XMCyber.Entity.averageComplexity
  description: Average complexity to compromise this entity
  type: number
- contextPath: XMCyber.Entity.criticalAssetsAtRisk
  description: Number of unique critical assets at risk from this entity
  type: number
- contextPath: XMCyber.Entity.averageComplexityLevel
  description: Level of the average complexity to compromise this entity
  type: string
- contextPath: XMCyber.Entity.id
  description: XMCyber Entity ID
  type: string
- contextPath: XMCyber.Entity.criticalAssetsAtRiskList
  description: Critical assets at risk from this entity
  type: unknown
- contextPath: XMCyber.Entity.entitiesAtRiskList
  description: Entities at risk from this entity
  type: unknown
